[2025-03-02T09:34:03.328+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T09:34:03.340+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection_task manual__2025-03-02T09:34:01.362169+00:00 [queued]>
[2025-03-02T09:34:03.347+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection_task manual__2025-03-02T09:34:01.362169+00:00 [queued]>
[2025-03-02T09:34:03.347+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-02T09:34:03.357+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): test_postgres_connection_task> on 2025-03-02 09:34:01.362169+00:00
[2025-03-02T09:34:03.362+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T09:34:03.364+0000] {standard_task_runner.py:72} INFO - Started process 160 to run task
[2025-03-02T09:34:03.364+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_connection', 'test_postgres_connection_task', 'manual__2025-03-02T09:34:01.362169+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/db_connection_test_dag.py', '--cfg-path', '/tmp/tmphldbrf02']
[2025-03-02T09:34:03.365+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask test_postgres_connection_task
[2025-03-02T09:34:03.399+0000] {task_command.py:467} INFO - Running <TaskInstance: test_postgres_connection.test_postgres_connection_task manual__2025-03-02T09:34:01.362169+00:00 [running]> on host 303421026b1b
[2025-03-02T09:34:03.458+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_connection' AIRFLOW_CTX_TASK_ID='test_postgres_connection_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T09:34:01.362169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T09:34:01.362169+00:00'
[2025-03-02T09:34:03.458+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T09:34:03.491+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-02T09:34:03.587+0000] {logging_mixin.py:190} INFO - Connection successful! Query result: (1,)
[2025-03-02T09:34:03.588+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T09:34:03.597+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T09:34:03.597+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=test_postgres_connection, task_id=test_postgres_connection_task, run_id=manual__2025-03-02T09:34:01.362169+00:00, execution_date=20250302T093401, start_date=20250302T093403, end_date=20250302T093403
[2025-03-02T09:34:03.632+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T09:34:03.644+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T09:34:03.645+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
